cc.exports["KBEngine"]= require("kbengine.kbengine")
require("lpack")
require("kbengine.bit")
require("kbengine.types")
require("kbengine.client_funs")
require("kbengine.math_extend")
KBEngine.Timer=require("kbengine.timer")
KBEngine.Bundle = require("kbengine.bundle")
KBEngine.Message = require("kbengine.message")
KBEngine.MemoryStream = require("kbengine.stream")
KBEngine.Entity = require("kbengine.entity")
KBEngine.EntityCall = require("kbengine.entity_call")
KBEngine.ServerErr=require("kbengine.server_err")
KBEngine.Event=require("kbengine.event")
KBEngine.Socket=require("kbengine.socket_tcp")
