KBEngine.GameObject=require("kbe_model.GameObject")
KBEngine.Account=require("kbe_model.Account")
KBEngine.Avatar=require("kbe_model.Avatar")
KBEngine.Gate=require("kbe_model.Gate")
KBEngine.Monster=require("kbe_model.Monster")
KBEngine.NPC=require("kbe_model.NPC")